/* Autogenerated skeleton program: test_gpio_negedge_intr_en */
#include "test_define.c"

void test_case(void)
{
    int errors = 0;

    DEBUG_DISPLAY("[GPIO] Start testcase: test_gpio_negedge_intr_en\n");

    /* TODO: Populate from Excel
     * - Description
     * - Procedure steps
     * - Impacted register list and per-register operations
     * - Acceptance criteria (increment errors on failure)
     */

    /* Dry-run: no register operations emitted. */

    if (errors == 0) {
        DEBUG_DISPLAY("[GPIO] PASS: test_gpio_negedge_intr_en\n");
        finish(0);
    } else {
        DEBUG_DISPLAY("[GPIO] FAIL: test_gpio_negedge_intr_en (errors=%d)\n", errors);
        finish(1);
    }
}
