// Auto-generated by Code_Generator Agent
// Source: 1774352477631/testcase_summary.csv
// Testcase: test_gpio_pedge_all_pads_en

#include "test_define.c"

static inline void DEBUG_DISPLAY(const char *fmt, ...) {
    va_list ap; va_start(ap, fmt); vprintf(fmt, ap); va_end(ap);
}

static inline uint32_t rd(uintptr_t a) { return *(volatile uint32_t*)a; }
static inline void wr(uintptr_t a, uint32_t v) { *(volatile uint32_t*)a = v; }

__attribute__((weak)) void Default_IRQHandler(void) {
    // CSV: set int_pend=0; read and mask group; clear per-pin raw and SYSREG; re-enable group
    int_pend = 0;
}

void test_case(void) {
    DEBUG_DISPLAY("[TEST] test_gpio_pedge_all_pads_en: start\n");

    unsigned test_err = 0u;

    // CSV: Configure posedge on each pin: write 0x00020000 to MIZAR_GPIO_GP0_GPIO_8+(i*4)
    // CSV: IO_CTRL_GROUP1..4 = 0x000000FF
    // CSV: GP0_INTR1_INTR_EN1 = 0xFFFFFFFF

    for (uint32_t i = 0; i < GPIO_PIN_COUNT; ++i) {
        int_pend = 1;
        // CSV: write PAD_DRIVE_REG low then high to create rising edge (symbolic only)
        uint32_t to = TIMEOUT_ITER;
        while (int_pend && to--) { /* spin */ }
        if (int_pend) {
            ++test_err;
            DEBUG_DISPLAY("[ERR] Timeout waiting for rising-edge interrupt on pin %u\n", i);
        }
        // CSV: drive low and continue
    }

    DEBUG_DISPLAY("[TEST] test_gpio_pedge_all_pads_en: %s\n", test_err?"FAIL":"PASS");
    finish(test_err ? 1 : 0);
}
