/* Autogenerated program for test_gpio_pedge_all_pads_en
 * CSV intent summary (comments only, no invented symbols):
 *  - Enable MIZAR_LSS_SYSREG_INTR_EN1 for GPIO interrupts
 *  - Configure posedge on each MIZAR_GPIO_GP0_GPIO_8+(i*4) by writing 0x00020000
 *  - Set MIZAR_GPIO_GPIO_IO_CTRL_GROUP1..4 = 0x000000FF
 *  - Enable MIZAR_GPIO_GP0_INTR1_INTR_EN1 = 0xFFFFFFFF
 *  - For each pin, generate rising edges using 0xA0243FFC
 *  - ISR validates MIZAR_GPIO_GP0_INTR1_INTR_STS1, clears per-pin and LSS_SYSREG RAW_STCR1, then re-enables INTR1_EN1
 */

#include "test_define.c"

volatile int int_pend = 0;

__attribute__((weak)) void GIC_EnableIRQ(int id) { (void)id; }
__attribute__((weak)) void GIC_ClearIRQ(int id) { (void)id; }
__attribute__((weak)) void finish(int status) {
    DEBUG_DISPLAY("Test finished with status=%d\n", status);
}

static inline void write_reg_u32(uintptr_t a, uint32_t v) { (void)a; (void)v; }
static inline uint32_t read_reg_u32(uintptr_t a) { (void)a; return 0u; }

__attribute__((weak)) void Default_IRQHandler(void) {
    /* CSV: set int_pend=0; read group status; mask, clear per-pin RAW; clear LSS_SYSREG RAW_STCR1; re-enable */
    int_pend = 0;
}

void test_case(void) {
    int test_err = 0;

    /* CSV sequence as comments, operations require platform symbols */
    /* Enable LSS_SYSREG_INTR_EN1 => TODO */

    /* Configure per-pin posedge */
    for (uint32_t i = 0; i < GPIO_PINS; ++i) {
        /* write MIZAR_GPIO_GP0_GPIO_8 + (i*4) = 0x00020000 */
    }

    /* IO_CTRL_GROUP1..4 = 0x000000FF */

    /* Enable GP0_INTR1_INTR_EN1 = 0xFFFFFFFF */

    for (uint32_t i = 0; i < GPIO_PINS; ++i) {
        /* Drive low then rising edge */
        write_reg_u32((uintptr_t)PAD_DRIVE_REG, 0x00000000u);
        int_pend = 1;
        write_reg_u32((uintptr_t)PAD_DRIVE_REG, 0xFFFFFFFFu);
        uint32_t to = POLL_TIMEOUT;
        while ((int_pend != 0) && (to-- > 0u)) { /* spin */ }
        if (int_pend != 0) {
            ++test_err;
            DEBUG_DISPLAY("[TIMEOUT] pin %u no interrupt observed\n", i);
            int_pend = 0;
        }
    }

    finish(test_err);
}
