/* Autogenerated from CSV 1774352477631/testcase_summary.csv
 * Testcase: test_gpio_pedge_all_pads_en
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
/* Optional HAL headers */
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

#ifndef GPIO_PINS
#define GPIO_PINS 32u
#endif
#ifndef PAD_DRIVE_REG
#define PAD_DRIVE_REG 0xA0243FFC /* TODO: replace with HAL define if available */
#endif
#ifndef POLL_TIMEOUT
#define POLL_TIMEOUT 1000000u
#endif
