// Auto-generated by Code_Generator Agent
// Source: 1774352477631/testcase_summary.csv
// Testcase: test_gpio_pedge_all_pads_en

#include <stdint.h>
#include <stdio.h>

// CSV-Referenced register macros (no invention):
// MIZAR_LSS_SYSREG_INTR_EN1
// MIZAR_GPIO_GP0_GPIO_8
// MIZAR_GPIO_GPIO_IO_CTRL_GROUP1
// MIZAR_GPIO_GPIO_IO_CTRL_GROUP2
// MIZAR_GPIO_GPIO_IO_CTRL_GROUP3
// MIZAR_GPIO_GPIO_IO_CTRL_GROUP4
// MIZAR_GPIO_GP0_INTR1_INTR_EN1
// MIZAR_GPIO_GP0_INTR1_INTR_STS1
// MIZAR_LSS_SYSREG_RAW_STCR1

static const uint32_t GPIO_PIN_COUNT = 32u;
static const uint32_t TIMEOUT_ITER = 1000000u; // simple spin timeout

volatile int int_pend = 0;
