/* Autogenerated by Code_Generator Agent (IST 12:14 26-03-2026)
 * Source Test Case: test_gpio_negedge_intr_en
 * Do not edit manually.
 */
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

#define CNT 6

const unsigned long int addr_array[CNT] = {
    MIZAR_LSS_SYSREG_INTR_EN1,
    MIZAR_GPIO_GP0_GPIO_8,
    MIZAR_GPIO_GPIO_INTR_RAW_STCLR1,
    MIZAR_GPIO_GP0_INTR1_INTR_EN1,
    MIZAR_GPIO_GP0_INTR1_INTR_STS1,
    MIZAR_LSS_SYSREG_RAW_STCR1
};

/* The following macros are expected to be provided by platform headers */
const unsigned int default_value_array[CNT] = {
    LSS_SYSREG_INTR_EN1_DEFAULT_VAL,
    GPIO_GP0_GPIO_8_DEFAULT_VAL,
    GPIO_GPIO_INTR_RAW_STCLR1_DEFAULT_VAL,
    GPIO_GP0_INTR1_INTR_EN1_DEFAULT_VAL,
    GPIO_GP0_INTR1_INTR_STS1_DEFAULT_VAL,
    LSS_SYSREG_RAW_STCR1_DEFAULT_VAL
};

const unsigned int read_mask_array[CNT] = {
    LSS_SYSREG_INTR_EN1_READ_MASK,
    GPIO_GP0_GPIO_8_READ_MASK,
    GPIO_GPIO_INTR_RAW_STCLR1_READ_MASK,
    GPIO_GP0_INTR1_INTR_EN1_READ_MASK,
    GPIO_GP0_INTR1_INTR_STS1_READ_MASK,
    LSS_SYSREG_RAW_STCR1_READ_MASK
};

const unsigned int write_mask_array[CNT] = {
    LSS_SYSREG_INTR_EN1_WRITE_MASK,
    GPIO_GP0_GPIO_8_WRITE_MASK,
    GPIO_GPIO_INTR_RAW_STCLR1_WRITE_MASK,
    GPIO_GP0_INTR1_INTR_EN1_WRITE_MASK,
    GPIO_GP0_INTR1_INTR_STS1_WRITE_MASK,
    LSS_SYSREG_RAW_STCR1_WRITE_MASK
};

const unsigned int skip_array[CNT]     = { 0 };
const unsigned int skip_rst_array[CNT] = { 0 };
