#include "test_define.c"

/* Autogenerated from CSV: test_gpio_pedge_all_pads_en */

static volatile int test_err = 0;
static volatile int int_pend = 0;

void Default_IRQHandler(void) {
    /* ISR behavior per CSV description */
    int_pend = 0;
}

void test_case(void)
{
#ifdef GPIO0
    GIC_EnableIRQ(87);
#endif
#ifdef GPIO1
    GIC_EnableIRQ(88);
#endif

    /* Enable system-level GPIO interrupts */
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, LSS_SYSREG_INTR_EN1_GPIO0_INTR | LSS_SYSREG_INTR_EN1_GPIO1_INTR);

    /* Configure posedge on all pins and enable IO_CTRL groups */
    for (int i = 0; i < 32; ++i) {
        write_reg(MIZAR_GPIO_GP0_GPIO_8 + (i * 4), 0x00020000);
        wait_on(1);
    }
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP1, 0x000000FF);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP2, 0x000000FF);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP3, 0x000000FF);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP4, 0x000000FF);
    wait_on(1);

    /* Enable all pins in group EN1 */
    write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 0xFFFFFFFF);

    for (int i = 0; i < 32; ++i) {
        /* Drive low to high transition using 0xA0243FFC */
        write_reg(0xA0243FFC, 0x00000000);
        wait_on(1);
        int_pend = 1;
        write_reg(0xA0243FFC, 0xFFFFFFFF);

        /* Poll with timeout to observe interrupt */
        int timeout = 1000000;
        while (int_pend && --timeout) { /* spin */ }
        if (timeout == 0) {
            printf("ERROR: timeout waiting for posedge interrupt on pin %d\n", i);
            test_err++;
            break;
        }

        /* Drive low again before moving on */
        write_reg(0xA0243FFC, 0x00000000);
        wait_on(1);
    }

    finish(test_err ? 1 : 0);
}
