/* Autogenerated GPIO testcase implementation: test_gpio_pedge_all_pads_en
 * Follows CSV procedure and acceptance criteria exactly. Do not edit manually.
 */

#include "test_define.c"

/* Globals */
static volatile int test_err = 0;
static volatile int int_pend = 0;

/* Small delay utility */
static inline void small_delay(void) {
    for (volatile unsigned int d = 0; d < 10000u; ++d) { __asm__ __volatile__("nop"); }
}

/* Helper: compute per-pin register address offset from base macro */
static inline unsigned int gpio_pin_reg(unsigned int i) {
    return (unsigned int)(MIZAR_GPIO_GP0_GPIO_8 + (i * 4u));
}

/* Default IRQ handler per CSV acceptance criteria */
void Default_IRQHandler(void) {
    int_pend = 0; /* ISR observed */

    unsigned int rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);

    /* Mask group to avoid re-entrant interrupts while servicing */
    write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 0x00000000u);

    if ((rdata_grp & 0xFFFFFFFFu) == 0u) {
        DEBUG_DISPLAY("[ISR] Expected non-zero group status prior to clear\n");
        test_err++;
    }

    /* Clear per-pin raw statuses by toggling mode as per CSV */
    for (unsigned int j = 0; j < 32u; ++j) {
        write_reg(gpio_pin_reg(j), 0x00010000u); /* clear posedge config per step */
        small_delay();
    }

    /* Verify group status reads 0 after clear */
    unsigned int rdata_grp_after = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
    if (rdata_grp_after != 0u) {
        DEBUG_DISPLAY("[ISR] Group status not cleared to 0 after per-pin clear\n");
        test_err++;
    }

    /* Clear sysreg and verify it does not retain bit */
    write_reg(MIZAR_LSS_SYSREG_RAW_STCR1, 0xFFFFFFFFu);
    unsigned int sysreg_chk = read_reg(MIZAR_LSS_SYSREG_RAW_STCR1);
    if (sysreg_chk != 0u) {
        DEBUG_DISPLAY("[ISR] SYSREG RAW_STCR1 retained bits after clear\n");
        test_err++;
    }

#ifdef GIC_ClearIRQ
    GIC_ClearIRQ(87);
    GIC_ClearIRQ(88);
#endif

    /* Re-enable group interrupts */
    write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 0xFFFFFFFFu);
}

void test_case(void) {
#ifdef GIC_EnableIRQ
    GIC_EnableIRQ(87);
    GIC_EnableIRQ(88);
#endif

    /* Enable GPIO interrupts in SYSREG */
    unsigned int en_mask = 0u;
#ifdef LSS_SYSREG_INTR_EN1_GPIO0_INTR
    en_mask |= LSS_SYSREG_INTR_EN1_GPIO0_INTR;
#endif
#ifdef LSS_SYSREG_INTR_EN1_GPIO1_INTR
    en_mask |= LSS_SYSREG_INTR_EN1_GPIO1_INTR;
#endif
    if (en_mask == 0u) {
        DEBUG_DISPLAY("[SETUP] SYSREG enable mask undefined; writing 0xFFFFFFFF as fallback\n");
        en_mask = 0xFFFFFFFFu;
    }
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, en_mask);

    /* Configure posedge on each pin and IO control groups */
    for (unsigned int i = 0; i < 32u; ++i) {
        write_reg(gpio_pin_reg(i), 0x00020000u);
        small_delay();
    }
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP1, 0x000000FFu);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP2, 0x000000FFu);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP3, 0x000000FFu);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP4, 0x000000FFu);
    small_delay();

    /* Enable group 1 interrupts for all pins */
    write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 0xFFFFFFFFu);

    /* For each pin: drive rising edge and poll for ISR */
    for (unsigned int i = 0; i < 32u; ++i) {
        /* Drive low, then rising edge on external pad model */
        *(volatile unsigned int *)0xA0243FFCu = 0x00000000u;
        small_delay();

        int_pend = 1;
        *(volatile unsigned int *)0xA0243FFCu = 0xFFFFFFFFu; /* rising edge */

        unsigned int to = 1000000u;
        while (int_pend && --to) { /* busy-wait */ }
        if (to == 0u) {
            DEBUG_DISPLAY("[POLL] Timeout waiting for ISR on pin %u (posedge)\n", i);
            test_err++;
            /* Continue with next pin after timeout as per CSV */
        }

        /* Drive low and continue */
        *(volatile unsigned int *)0xA0243FFCu = 0x00000000u;
    }

    finish(test_err);
}
