/* Autogenerated GPIO testcase: test_gpio_pedge_all_pads_en
 * Do not edit manually. Generated by Code_Generator Agent.
 */

#include <stdio.h>
#include <lss_sysreg.h>
#include <test_common.h>
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/* Local defines from helper */
#ifndef CNT
#define CNT 49
#endif

/* Impacted register macros used by this testcase.
 * Build should provide these via included headers. Add guards to surface missing defines.
 */
#ifndef MIZAR_LSS_SYSREG_INTR_EN1
#warning "MIZAR_LSS_SYSREG_INTR_EN1 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GP0_GPIO_8
#warning "MIZAR_GPIO_GP0_GPIO_8 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GPIO_IO_CTRL_GROUP1
#warning "MIZAR_GPIO_GPIO_IO_CTRL_GROUP1 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GPIO_IO_CTRL_GROUP2
#warning "MIZAR_GPIO_GPIO_IO_CTRL_GROUP2 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GPIO_IO_CTRL_GROUP3
#warning "MIZAR_GPIO_GPIO_IO_CTRL_GROUP3 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GPIO_IO_CTRL_GROUP4
#warning "MIZAR_GPIO_GPIO_IO_CTRL_GROUP4 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GP0_INTR1_INTR_EN1
#warning "MIZAR_GPIO_GP0_INTR1_INTR_EN1 not defined by included headers"
#endif
#ifndef MIZAR_GPIO_GP0_INTR1_INTR_STS1
#warning "MIZAR_GPIO_GP0_INTR1_INTR_STS1 not defined by included headers"
#endif
#ifndef MIZAR_LSS_SYSREG_RAW_STCR1
#warning "MIZAR_LSS_SYSREG_RAW_STCR1 not defined by included headers"
#endif

/* Skip list mapping: index corresponds to the position of the register in CSV Impacted Registers list */
static unsigned int skip_array[9] = {
    /* [0] MIZAR_LSS_SYSREG_INTR_EN1              */ 0u,
    /* [1] MIZAR_GPIO_GP0_GPIO_8                  */ 0u,
    /* [2] MIZAR_GPIO_GPIO_IO_CTRL_GROUP1         */ 0u,
    /* [3] MIZAR_GPIO_GPIO_IO_CTRL_GROUP2         */ 0u,
    /* [4] MIZAR_GPIO_GPIO_IO_CTRL_GROUP3         */ 0u,
    /* [5] MIZAR_GPIO_GPIO_IO_CTRL_GROUP4         */ 0u,
    /* [6] MIZAR_GPIO_GP0_INTR1_INTR_EN1          */ 0u,
    /* [7] MIZAR_GPIO_GP0_INTR1_INTR_STS1         */ 0u,
    /* [8] MIZAR_LSS_SYSREG_RAW_STCR1             */ 0u
};

/* Register specification map (from Impacted_Register_Spec_RAG)
 * NOTE: RAG data was unavailable at generation time; populate later if needed.
 * - MIZAR_LSS_SYSREG_INTR_EN1: [spec TBD]
 * - MIZAR_GPIO_GP0_GPIO_8: [spec TBD]
 * - MIZAR_GPIO_GPIO_IO_CTRL_GROUP1: [spec TBD]
 * - MIZAR_GPIO_GPIO_IO_CTRL_GROUP2: [spec TBD]
 * - MIZAR_GPIO_GPIO_IO_CTRL_GROUP3: [spec TBD]
 * - MIZAR_GPIO_GPIO_IO_CTRL_GROUP4: [spec TBD]
 * - MIZAR_GPIO_GP0_INTR1_INTR_EN1: [spec TBD]
 * - MIZAR_GPIO_GP0_INTR1_INTR_STS1: [spec TBD]
 * - MIZAR_LSS_SYSREG_RAW_STCR1: [spec TBD]
 */
