// Auto-generated by Code_Generator Agent
// Source: 1774352477631/testcase_summary.csv
// Testcase: test_gpio_negedge_intr_en
// Only include "test_define.c" per run spec. Implement void test_case(void) as the entry.

#include "test_define.c"

static inline void DEBUG_DISPLAY(const char *fmt, ...) {
    va_list ap; va_start(ap, fmt); vprintf(fmt, ap); va_end(ap);
}

// Per spec, do not invent register addresses or macros; operate symbolically with macros only in comments.
// The following helper uses placeholder volatile pointers when addresses are unknown. Real platform should provide defines.
static inline uint32_t rd(uintptr_t a) { return *(volatile uint32_t*)a; }
static inline void wr(uintptr_t a, uint32_t v) { *(volatile uint32_t*)a = v; }

// Weak ISR symbol as per CSV; platform may override linkage.
__attribute__((weak)) void Default_IRQHandler(void) {
    // CSV: set int_pend=0; validate/clear per-pin and group; acknowledge SYSREG and clear GIC
    int_pend = 0;
    // Without concrete addresses, we cannot perform actual register I/O here per non-invention rule.
}

void test_case(void) {
    DEBUG_DISPLAY("[TEST] test_gpio_negedge_intr_en: start\n");

    // CSV: Optionally GIC_EnableIRQ(87/88). Not emitted to avoid introducing undefined symbols.
    // CSV: Enable MIZAR_LSS_SYSREG_INTR_EN1 with GPIOx_INTR enable (symbolic only).
    // CSV: write PAD_DRIVE_REG=0xFFFFFFFF (symbolic; no address invention)

    unsigned test_err = 0u;

    for (uint32_t i = 0; i < GPIO_PIN_COUNT; ++i) {
        // CSV: Configure per-pin at MIZAR_GPIO_GP0_GPIO_8 + (i*4) with bits (1u<<20)|(1u<<18)|(1u<<16)
        // CSV: Clear raw status via MIZAR_GPIO_GPIO_INTR_RAW_STCLR1 = (1u<<i)
        // CSV: Enable per-pin MIZAR_GPIO_GP0_INTR1_INTR_EN1 = (1u<<i)

        int_pend = 1;
        // CSV: Drive edges via PAD_DRIVE_REG toggling: write 0xFFFFFFFF then ~wr_val
        // Symbolic only; no address writes due to non-invention rule.

        // Poll with timeout
        uint32_t to = TIMEOUT_ITER;
        while (int_pend && to--) { /* spin */ }
        if (int_pend) {
            ++test_err;
            DEBUG_DISPLAY("[ERR] Timeout waiting for interrupt on pin %u\n", i);
        }
    }

    DEBUG_DISPLAY("[TEST] test_gpio_negedge_intr_en: %s\n", test_err?"FAIL":"PASS");
    finish(test_err ? 1 : 0);
}
