/* Autogenerated program for test_gpio_negedge_intr_en
 * CSV intent:
 *  - Enable LSS_SYSREG_INTR_EN1 for GPIO interrupts
 *  - Configure per-pin at MIZAR_GPIO_GP0_GPIO_8 + (i*4): set (1u<<20)|(1u<<18)|(1u<<16)
 *  - Enable MIZAR_GPIO_GP0_INTR1_INTR_EN1 per pin
 *  - Toggle PAD_DRIVE_REG (0xA0243FFC) to create edges
 *  - ISR (Default_IRQHandler): validate status, clear RAW_STCLR1 and LSS_SYSREG_RAW_STCR1
 */

#include "test_define.c"

/* Shared volatile flag set/cleared by ISR */
volatile int int_pend = 0;

/* Weak hooks to be provided by platform if available */
__attribute__((weak)) void GIC_EnableIRQ(int id) { (void)id; }
__attribute__((weak)) void GIC_ClearIRQ(int id) { (void)id; }
__attribute__((weak)) void finish(int status) {
    DEBUG_DISPLAY("Test finished with status=%d\n", status);
}

static inline void write_reg_u32(uintptr_t a, uint32_t v) { (void)a; (void)v; }
static inline uint32_t read_reg_u32(uintptr_t a) { (void)a; return 0u; }

/* ISR skeleton per CSV; platform must wire this to the actual vector */
__attribute__((weak)) void Default_IRQHandler(void) {
    /* CSV: set int_pend=0; validate per-pin state; check INTR1_STS1 bit; clear RAW_STCLR1; ack SYSREG RAW_STCR1; clear GIC IRQ */
    int_pend = 0;
}

void test_case(void) {
    int test_err = 0;

    /* Optional: enable IRQ lines */
    GIC_EnableIRQ(IRQ_GPIO0);
    GIC_EnableIRQ(IRQ_GPIO1);

    /* CSV: write MIZAR_LSS_SYSREG_INTR_EN1 with LSS_SYSREG_INTR_EN1_GPIOx_INTR (symbol not available here) */

    /* Drive all-high first */
    write_reg_u32((uintptr_t)PAD_DRIVE_REG, 0xFFFFFFFFu);

    for (uint32_t i = 0; i < GPIO_PINS; ++i) {
        /* CSV: write MIZAR_GPIO_GP0_GPIO_8 + (i*4) with (1u<<20)|(1u<<18)|(1u<<16) */
        /* Clear RAW_STCLR1 for this pin and enable INTR1_EN1 for pin i */

        /* Create falling edge on pin i by toggling PAD_DRIVE_REG */
        uint32_t wr_val = (1u << i);
        /* Clear raw status and enable per-pin: symbols not available; represented as comments per CSV */
        
        int_pend = 1;
        /* Drive high then invert only this bit to low */
        write_reg_u32((uintptr_t)PAD_DRIVE_REG, 0xFFFFFFFFu);
        /* Small wait could be inserted if needed */
        write_reg_u32((uintptr_t)PAD_DRIVE_REG, ~wr_val);

        /* Poll int_pend with timeout */
        uint32_t to = POLL_TIMEOUT;
        while ((int_pend != 0) && (to-- > 0u)) { /* spin */ }
        if (int_pend != 0) {
            ++test_err;
            DEBUG_DISPLAY("[TIMEOUT] pin %u no interrupt observed\n", i);
            int_pend = 0; /* avoid hanging next loop */
        }
    }

    finish(test_err);
}
