/* Autogenerated from CSV 1774352477631/testcase_summary.csv
 * Testcase: test_gpio_negedge_intr_en
 * Includes, macro defines, constants and TODOs.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
/* Optional HAL headers */
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/* Macro defines from helper (none provided; using placeholders to keep buildable) */
#ifndef GPIO_PINS
#define GPIO_PINS 32u
#endif
#ifndef IRQ_GPIO0
#define IRQ_GPIO0 87 /* TODO: verify */
#endif
#ifndef IRQ_GPIO1
#define IRQ_GPIO1 88 /* TODO: verify */
#endif
#ifndef PAD_DRIVE_REG
#define PAD_DRIVE_REG 0xA0243FFC /* TODO: replace with HAL define if available */
#endif

/* Timeouts and small waits (arbitrary safe defaults) */
#ifndef POLL_TIMEOUT
#define POLL_TIMEOUT 1000000u
#endif

/* No authoritative register addresses available at generation time.
 * program.c will use CSV-specified macros as comments and follow the flow with TODOs.
 */
