// Auto-generated by Code_Generator Agent
// Source: 1774352477631/testcase_summary.csv
// Testcase: test_gpio_negedge_intr_en
// Per run spec, includes, defines, arrays, and skip list must be local to test_define.c

#include <stdint.h>
#include <stdio.h>

// Helper-provided includes and macros were unavailable via agent; keeping minimal set.
// TODO: Insert platform headers if provided by Code_Gen_Helper in a future pass.

// CSV-Referenced register macros (no invention):
// MIZAR_LSS_SYSREG_INTR_EN1
// MIZAR_GPIO_GP0_GPIO_8
// MIZAR_GPIO_GPIO_INTR_RAW_STCLR1
// MIZAR_GPIO_GP0_INTR1_INTR_EN1
// MIZAR_GPIO_GP0_INTR1_INTR_STS1
// MIZAR_LSS_SYSREG_RAW_STCR1

// Test constants
static const uint32_t GPIO_PIN_COUNT = 32u;
static const uint32_t TIMEOUT_ITER = 1000000u; // simple spin timeout

// Accept CSV semantics: int_pend is polled by the test and cleared in Default_IRQHandler
volatile int int_pend = 0;

// No arrays needed beyond constants for this interrupt test case based on CSV procedure
