#include "test_define.c"

/* Autogenerated from CSV procedure for test_gpio_pedge_all_pads_en */

static volatile int int_pend = 0;
static int test_err = 0;

static void poll_for_interrupt_or_timeout(void)
{
    int timeout = 1000000;
    while (timeout-- > 0) {
        if (int_pend == 0) return;
    }
#ifdef DEBUG_DISPLAY
    printf("Timeout while polling for posedge interrupt\n");
#endif
    test_err++;
}

void Default_IRQHandler(void)
{
    /* mask interrupts and snapshot status */
    write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 0x00000000u);
    unsigned rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
    if ((rdata_grp & 0xFFFFFFFFu) == 0u) {
        test_err++;
    }

    /* clear per-pin edge config */
    for (unsigned j = 0; j < 32; ++j) {
        write_reg(MIZAR_GPIO_GP0_GPIO_8 + (j * 4), 0x00010000u);
    }

    rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
    if (rdata_grp != 0u) { test_err++; }

    /* acknowledge at SYSREG level: placeholder */
    /* TODO: write correct bit(s) into MIZAR_LSS_SYSREG_RAW_STCR1 per platform macro */

#ifdef GPIO0
    GIC_ClearIRQ(87);
#endif
#ifdef GPIO1
    GIC_ClearIRQ(88);
#endif

    int_pend = 0;
}

void test_case(void)
{
#ifdef GPIO0
    GIC_EnableIRQ(87);
#endif
#ifdef GPIO1
    GIC_EnableIRQ(88);
#endif

    /* Enable LSS SYSREG GPIO interrupts */
    unsigned en = read_reg(MIZAR_LSS_SYSREG_INTR_EN1);
    en |= (LSS_SYSREG_INTR_EN1_GPIO0_INTR | LSS_SYSREG_INTR_EN1_GPIO1_INTR);
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, en);

    /* Configure posedge on all pins, IO control groups, and enable group interrupts */
    for (unsigned i = 0; i < 32; ++i) {
        write_reg(MIZAR_GPIO_GP0_GPIO_8 + (i * 4), 0x00020000u);
    }

    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP1, 0x000000FFu);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP2, 0x000000FFu);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP3, 0x000000FFu);
    write_reg(MIZAR_GPIO_GPIO_IO_CTRL_GROUP4, 0x000000FFu);

    write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, 0xFFFFFFFFu);

    for (unsigned i = 0; i < 32; ++i) {
        write_reg(0xA0243FFC, 0x00000000u);
        int_pend = 1;
        write_reg(0xA0243FFC, 0xFFFFFFFFu);
        poll_for_interrupt_or_timeout();
        write_reg(0xA0243FFC, 0x00000000u);
    }

    if (test_err == 0) finish(0); else finish(1);
}
