#include "test_define.c"

/* Autogenerated from CSV procedure for test_gpio_negedge_intr_en */

static volatile int int_pend = 0;
static int test_err = 0;

static void poll_for_interrupt_or_timeout(unsigned bit)
{
    int timeout = 1000000; /* simple spin timeout */
    while (timeout-- > 0) {
        if (int_pend == 0) return; /* cleared by ISR */
    }
#ifdef DEBUG_DISPLAY
    printf("Timeout while polling for negedge interrupt on bit %u\n", bit);
#endif
    test_err++;
}

void Default_IRQHandler(void)
{
    /* ISR behavior per CSV: check per-pin state and group status, then clear */
    unsigned i = 0; /* if caller sets context of current pin index, replace as needed */
    unsigned rdata = read_reg(MIZAR_GPIO_GP0_GPIO_8 + (i * 4));
    if ((rdata & 0x1u) != 0) { test_err++; }
    if ((rdata & 0x2u) == 0) { test_err++; }

    unsigned rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
    if ((rdata_grp & (1u << i)) == 0u) { test_err++; }

    /* clear pin edge config sticky as described */
    write_reg(MIZAR_GPIO_GP0_GPIO_8 + (i * 4), (1u << 20) | (1u << 16));
    /* clear RAW STS for that bit */
    write_reg(MIZAR_GPIO_GPIO_INTR_RAW_STCLR1, (1u << i));

    rdata_grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
    if (rdata_grp != 0u) { test_err++; }

    /* acknowledge at SYSREG level */
    /* TODO: write correct bit(s) into MIZAR_LSS_SYSREG_RAW_STCR1 per platform macro */
    /* write_reg(MIZAR_LSS_SYSREG_RAW_STCR1, LSS_SYSREG_RAW_STCR1_GPIO0_INTR | LSS_SYSREG_RAW_STCR1_GPIO1_INTR); */

#ifdef GPIO0
    GIC_ClearIRQ(87);
#endif
#ifdef GPIO1
    GIC_ClearIRQ(88);
#endif

    int_pend = 0; /* indicate to poller that IRQ arrived */
}

void test_case(void)
{
#ifdef GPIO0
    GIC_EnableIRQ(87);
#endif
#ifdef GPIO1
    GIC_EnableIRQ(88);
#endif

    /* Enable LSS SYSREG GPIO interrupts */
    unsigned en = read_reg(MIZAR_LSS_SYSREG_INTR_EN1);
    /* Assuming macros exist in lss_sysreg.h */
    en |= (LSS_SYSREG_INTR_EN1_GPIO0_INTR | LSS_SYSREG_INTR_EN1_GPIO1_INTR);
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, en);

    /* Configure all 32 pins: negedge enable + clear raw and enable per-pin */
    for (unsigned i = 0; i < 32; ++i) {
        write_reg(MIZAR_GPIO_GP0_GPIO_8 + (i * 4), (1u << 20) | (1u << 18) | (1u << 16));
    }

    for (unsigned i = 0; i < 32; ++i) {
        unsigned wr_val = (1u << i);
        write_reg(MIZAR_GPIO_GPIO_INTR_RAW_STCLR1, wr_val);
        write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, wr_val);

        int_pend = 1;
        /* create negedge on single bit i using external drive register */
        write_reg(0xA0243FFC, 0xFFFFFFFFu);
        /* drive bit i low to create falling edge */
        write_reg(0xA0243FFC, ~wr_val);

        poll_for_interrupt_or_timeout(i);
    }

    if (test_err == 0) finish(0); else finish(1);
}
