/* Autogenerated skeleton test definitions: gpio_reg_wr_rd_test */
#ifndef TEST_DEFINE_C_INCLUDED
#define TEST_DEFINE_C_INCLUDED

#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include "test_define.c"
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/* Macros provided by helper (verbatim) */
#define SOFT_RST_REG_ADDRESS 0x00000000
#define SOFT_RST_REG_DATA 0x00000000
#define CNT 49

/* Infrastructure fallbacks (non-register) */
#ifndef DEBUG_DISPLAY
#define DEBUG_DISPLAY(...) printf(__VA_ARGS__)
#endif

/* Test harness finish hook (provided by environment) */
extern void finish(int status);

/* NOTE: This is a dry-run skeleton. Impacted registers, description, procedure,
 * and acceptance criteria must be populated from Excel in a non-dry-run. */

#endif /* TEST_DEFINE_C_INCLUDED */
