/* Autogenerated program for gpio_reg_wr_rd_test
 * Mirrors CSV procedure:
 * - Validate reset values using default_value_array with a pre-mask of 0xFFFFFFFE
 * - Perform masked write/read using write_mask_array and read_mask_array
 * - Maintain def_fail_cnt and wr_fail_cnt and call finish(0/1)
 * Arrays and CNT are provided by test_define.c
 */

#include "test_define.c"

static int def_fail_cnt = 0;
static int wr_fail_cnt = 0;

static void chk_rst_val(void) {
    for (uint32_t i = 0; i < CNT; ++i) {
        if (skip_rst_array[i]) { DEBUG_DISPLAY("[RST] skip_rst[%u] -> skipped\n", i); continue; }
        if (read_mask_array[i] == 0u) { DEBUG_DISPLAY("[RST] read_mask[0] idx %u -> skipped\n", i); continue; }
        uintptr_t addr = addr_array[i];
        uint32_t data_rd = 0u;
        /* Without authoritative addresses, reads will be zero; arrays are zero-initialized intentionally */
        (void)addr; /* silence unused if arrays are placeholder */
        /* Apply special mask 0xFFFFFFFE per CSV before comparing to default */
        uint32_t data = (data_rd & 0xFFFFFFFEu);
        uint32_t exp  = default_value_array[i];
        if (data != exp) {
            ++def_fail_cnt;
            DEBUG_DISPLAY("[RST][FAIL] idx=%u data=0x%08X exp=0x%08X\n", i, data, exp);
        } else {
            DEBUG_DISPLAY("[RST][OK]   idx=%u data=0x%08X\n", i, data);
        }
    }
}

static void chk_rd_wr(void) {
    const uint32_t patterns[] = {
        0xFFFFFFFFu, 0xAAAAAAA Au, 0x55555555u, 0xF5F5F5F5u, 0xA5A5A5A5u, 0xFFFF0000u
    };
    const size_t np = sizeof(patterns)/sizeof(patterns[0]);

    for (size_t p = 0; p < np; ++p) {
        uint32_t data_wr = patterns[p];
        /* First pass: perform masked writes */
        for (uint32_t i = 0; i < CNT; ++i) {
            if (skip_array[i]) { DEBUG_DISPLAY("[WR] skip[%u] -> skipped\n", i); continue; }
            if (write_mask_array[i] == 0u) { DEBUG_DISPLAY("[WR] write_mask[0] idx %u -> skipped\n", i); continue; }
            uintptr_t addr = addr_array[i];
            uint32_t w = (data_wr & write_mask_array[i]);
            (void)addr; (void)w; /* placeholder: no MMIO without specs */
        }
        /* Second pass: readback and compare */
        for (uint32_t i = 0; i < CNT; ++i) {
            if (skip_array[i]) continue;
            if (write_mask_array[i] == 0u || read_mask_array[i] == 0u) continue;
            uintptr_t addr = addr_array[i];
            uint32_t data_rd = 0u; (void)addr;
            uint32_t wr_n = (write_mask_array[i] ^ 0xFFFFFFFFu);
            uint32_t exp_val = ((data_wr & read_mask_array[i] & write_mask_array[i]) |
                                (wr_n    & read_mask_array[i] & default_value_array[i]));
            data_rd &= read_mask_array[i];
            if (data_rd != exp_val) {
                ++wr_fail_cnt;
                DEBUG_DISPLAY("[RD][FAIL] p=%zu idx=%u rd=0x%08X exp=0x%08X\n", p, i, data_rd, exp_val);
            } else {
                DEBUG_DISPLAY("[RD][OK]   p=%zu idx=%u val=0x%08X\n", p, i, data_rd);
            }
        }
    }
}

void test_case(void) {
    def_fail_cnt = 0; wr_fail_cnt = 0;
    chk_rst_val();
    chk_rd_wr();
    if ((def_fail_cnt > 0) || (wr_fail_cnt > 0)) {
        DEBUG_DISPLAY("[RESULT] FAIL def=%d wr=%d\n", def_fail_cnt, wr_fail_cnt);
        finish(1);
    } else {
        DEBUG_DISPLAY("[RESULT] PASS\n");
        finish(0);
    }
}
