// Auto-generated by Code_Generator Agent
// Source: 1774352477631/testcase_summary.csv
// Testcase: gpio_reg_wr_rd_test
// Program entry adheres to the run spec: #include "test_define.c" and void test_case(void)
// Implements CSV procedure and acceptance criteria exactly; uses DEBUG_DISPLAY for logs.

#include "test_define.c"

// Local counters
static int def_fail_cnt = 0;
static int wr_fail_cnt  = 0;

static inline void DEBUG_DISPLAY(const char *fmt, ...) {
    va_list ap; va_start(ap, fmt); vprintf(fmt, ap); va_end(ap);
}

// Stub MMIO helpers. If platform provides read_reg/write_reg, they should
// be visible through included headers in test_define.c. Otherwise, provide
// minimal volatile access here under unique names to avoid conflicts.
static inline uint32_t __mmio_read32(uintptr_t a) { return *(volatile uint32_t *)a; }
static inline void     __mmio_write32(uintptr_t a, uint32_t v) { *(volatile uint32_t *)a = v; }

static uint32_t read_reg_fallback(uintptr_t a) { return __mmio_read32(a); }
static void     write_reg_fallback(uintptr_t a, uint32_t v) { __mmio_write32(a, v); }

#ifndef finish
// Minimal finish if platform did not provide one via headers
static void finish(int status) {
    DEBUG_DISPLAY("\n[TEST] finish(%d)\n", status);
}
#endif

// CSV step: Call chk_rst_val(); compare masked read (0xFFFFFFFE) against default_value_array
static void chk_rst_val(void) {
    for (size_t i = 0; i < CNT; ++i) {
        if (skip_rst_array[i]) { continue; }
        if (read_mask_array[i] == 0u) { continue; }
        const uintptr_t addr = addr_array[i];
        uint32_t data_rd = read_reg_fallback(addr);
        uint32_t data = (data_rd & 0xFFFFFFFEu); // per CSV
        uint32_t expect = default_value_array[i];
        if (data != expect) {
            ++def_fail_cnt;
            DEBUG_DISPLAY("[DEF-MISMATCH] idx=%zu addr=0x%08lX rd=0x%08X exp=0x%08X\n",
                          i, (unsigned long)addr, data, expect);
        }
    }
}

// CSV step: Masked write/readback across patterns with acceptance criteria
static void chk_rd_wr(void) {
    const uint32_t patterns[] = {
        0xFFFFFFFFu, 0xAAAAAAAAu, 0x55555555u,
        0xF5F5F5F5u, 0xA5A5A5A5u, 0xFFFF0000u
    };

    for (size_t p = 0; p < sizeof(patterns)/sizeof(patterns[0]); ++p) {
        uint32_t data_wr = patterns[p];
        // Write phase
        for (size_t i = 0; i < CNT; ++i) {
            if (skip_array[i]) { continue; }
            if (write_mask_array[i] == 0u) { continue; }
            const uintptr_t addr = addr_array[i];
            uint32_t w = (data_wr & write_mask_array[i]);
            write_reg_fallback(addr, w);
        }

        // Read/verify phase
        for (size_t i = 0; i < CNT; ++i) {
            if (skip_array[i]) { continue; }
            if (write_mask_array[i] == 0u || read_mask_array[i] == 0u) { continue; }
            const uintptr_t addr = addr_array[i];
            uint32_t data_rd = (read_reg_fallback(addr) & read_mask_array[i]);
            uint32_t wr_n = (write_mask_array[i] ^ 0xFFFFFFFFu);
            uint32_t exp_val = ((data_wr & read_mask_array[i] & write_mask_array[i]) |
                                (wr_n     & read_mask_array[i] & default_value_array[i]));
            if (data_rd != exp_val) {
                ++wr_fail_cnt;
                DEBUG_DISPLAY("[WR-MISMATCH] pat=%zu idx=%zu addr=0x%08lX rd=0x%08X exp=0x%08X rm=0x%08X wm=0x%08X\n",
                              p, i, (unsigned long)addr, data_rd, exp_val,
                              read_mask_array[i], write_mask_array[i]);
            }
        }
    }
}

void test_case(void) {
    DEBUG_DISPLAY("[TEST] gpio_reg_wr_rd_test: start\n");
    chk_rst_val();
    chk_rd_wr();
    int status = (def_fail_cnt == 0 && wr_fail_cnt == 0) ? 0 : 1;
    DEBUG_DISPLAY("[TEST] gpio_reg_wr_rd_test: def_fail_cnt=%d wr_fail_cnt=%d => %s\n",
                  def_fail_cnt, wr_fail_cnt, status==0?"PASS":"FAIL");
    finish(status);
}
