/* Autogenerated from CSV 1774352477631/testcase_summary.csv
 * Testcase: gpio_reg_wr_rd_test
 * This file aggregates includes, macro defines, and test arrays.
 * NOTE: Register specs were not available from RAG at generation time.
 *       Arrays are initialized to zero with masks set to 0 so program.c will skip operations.
 *       Fill with real values when available.
 */

/* Header includes supplied/assumed by Code_Gen_Helper/messages context */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
/* Attempt to include GPIO headers if present in the repository */
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

/* Macro defines supplied by Code_Gen_Helper (assumed) */
#ifndef CNT
#define CNT 49u
#endif

/* Impacted Registers order (from CSV), indices 0..48:
   0: MIZAR_GPIO_GP0_GPIO_8
   1: MIZAR_GPIO_GP0_GPIO_9
   2: MIZAR_GPIO_GP0_GPIO_10
   3: MIZAR_GPIO_GP0_GPIO_11
   4: MIZAR_GPIO_GP0_GPIO_12
   5: MIZAR_GPIO_GP0_GPIO_13
   6: MIZAR_GPIO_GP0_GPIO_14
   7: MIZAR_GPIO_GP0_GPIO_15
   8: MIZAR_GPIO_GP0_GPIO_16
   9: MIZAR_GPIO_GP0_GPIO_17
  10: MIZAR_GPIO_GP0_GPIO_18
  11: MIZAR_GPIO_GP0_GPIO_19
  12: MIZAR_GPIO_GP0_GPIO_20
  13: MIZAR_GPIO_GP0_GPIO_21
  14: MIZAR_GPIO_GP0_GPIO_22
  15: MIZAR_GPIO_GP0_GPIO_23
  16: MIZAR_GPIO_GP0_GPIO_24
  17: MIZAR_GPIO_GP0_GPIO_25
  18: MIZAR_GPIO_GP0_GPIO_26
  19: MIZAR_GPIO_GP0_GPIO_27
  20: MIZAR_GPIO_GP0_GPIO_28
  21: MIZAR_GPIO_GP0_GPIO_29
  22: MIZAR_GPIO_GP0_GPIO_30
  23: MIZAR_GPIO_GP0_GPIO_31
  24: MIZAR_GPIO_GP0_GPIO_32
  25: MIZAR_GPIO_GP0_GPIO_33
  26: MIZAR_GPIO_GP0_GPIO_34
  27: MIZAR_GPIO_GP0_GPIO_35
  28: MIZAR_GPIO_GP0_GPIO_36
  29: MIZAR_GPIO_GP0_GPIO_37
  30: MIZAR_GPIO_GP0_GPIO_38
  31: MIZAR_GPIO_GP0_GPIO_39
  32: MIZAR_GPIO_GPIO_INTR_RAW_STCLR1
  33: MIZAR_GPIO_GP0_INTR1_INTR_EN1
  34: MIZAR_GPIO_GP0_INTR1_INTR_STS1
  35: MIZAR_GPIO_GP0_INTR2_INTR_EN1
  36: MIZAR_GPIO_GP0_INTR2_INTR_STS1
  37: MIZAR_GPIO_GPIO_IO_CTRL_GROUP1
  38: MIZAR_GPIO_GPIO_IO_CTRL_GROUP2
  39: MIZAR_GPIO_GPIO_IO_CTRL_GROUP3
  40: MIZAR_GPIO_GPIO_IO_CTRL_GROUP4
  41: MIZAR_GPIO_GPIO_DOUT_GROUP1
  42: MIZAR_GPIO_GPIO_DOUT_GROUP2
  43: MIZAR_GPIO_GPIO_DOUT_GROUP3
  44: MIZAR_GPIO_GPIO_DOUT_GROUP4
  45: MIZAR_GPIO_GPIO_DIN_GROUP1
  46: MIZAR_GPIO_GPIO_DIN_GROUP2
  47: MIZAR_GPIO_GPIO_DIN_GROUP3
  48: MIZAR_GPIO_GPIO_DIN_GROUP4
*/

/* Authoritative register map was unavailable. Initialize arrays conservatively. */
const uintptr_t addr_array[CNT] = {0};
const uint32_t default_value_array[CNT] = {0};
/* Masks set to 0 so program.c skips operations until real masks are provided */
const uint32_t read_mask_array[CNT] = {0};
const uint32_t write_mask_array[CNT] = {0};

/* Skip arrays: mark known W1C/side-effect/group registers as skipped when known.
 * If unsure, leave 0; program.c will also skip due to zero masks above.
 */
const uint8_t skip_rst_array[CNT] = {0};
const uint8_t skip_array[CNT] = {
  /* 0..31 per-pin CFG: default 0 (not skipped) */
  [0 ... 31] = 0,
  /* Group/RAW/IO/DIN/DOUT typically not safe for patterned writes: skip them */
  [32] = 1, /* RAW_STCLR1 */
  [33] = 1, /* INTR1_EN1 */
  [34] = 1, /* INTR1_STS1 */
  [35] = 1, /* INTR2_EN1 */
  [36] = 1, /* INTR2_STS1 */
  [37] = 1, [38] = 1, [39] = 1, [40] = 1, /* IO_CTRL_GROUP1..4 */
  [41] = 1, [42] = 1, [43] = 1, [44] = 1, /* DOUT_GROUP1..4 */
  [45] = 1, [46] = 1, [47] = 1, [48] = 1  /* DIN_GROUP1..4 */
};
