// Auto-generated by Code_Generator Agent
// Source: 1774352477631/testcase_summary.csv
// Testcase: gpio_reg_wr_rd_test
// Notes:
// - Header includes, macro defines, and skip register list are taken from Code_Gen_Helper output.
// - Arrays are sized to the CSV Impacted Registers list (CNT = 49).
// - Per run spec, values are not invented; unknown addresses/defaults are set to 0 with TODO notes.

#include <stdio.h>
#include <stdlib.h>
#include "test_common.h"
#include "test_define.c" // As provided by helper output; retained verbatim
#include <gpio/gpio_def.h>
#include <gpio/gpio_offset.h>

// Helper-provided macro defines
#define SOFT_RST_REG_ADDRESS  0x00000000
#define SOFT_RST_REG_DATA     0x00000000
#define CNT 49

#include <stdint.h>
#include <stddef.h>

// Impacted registers in CSV order (index -> macro)
//  0: MIZAR_GPIO_GP0_GPIO_8
//  1: MIZAR_GPIO_GP0_GPIO_9
//  2: MIZAR_GPIO_GP0_GPIO_10
//  3: MIZAR_GPIO_GP0_GPIO_11
//  4: MIZAR_GPIO_GP0_GPIO_12
//  5: MIZAR_GPIO_GP0_GPIO_13
//  6: MIZAR_GPIO_GP0_GPIO_14
//  7: MIZAR_GPIO_GP0_GPIO_15
//  8: MIZAR_GPIO_GP0_GPIO_16
//  9: MIZAR_GPIO_GP0_GPIO_17
// 10: MIZAR_GPIO_GP0_GPIO_18
// 11: MIZAR_GPIO_GP0_GPIO_19
// 12: MIZAR_GPIO_GP0_GPIO_20
// 13: MIZAR_GPIO_GP0_GPIO_21
// 14: MIZAR_GPIO_GP0_GPIO_22
// 15: MIZAR_GPIO_GP0_GPIO_23
// 16: MIZAR_GPIO_GP0_GPIO_24
// 17: MIZAR_GPIO_GP0_GPIO_25
// 18: MIZAR_GPIO_GP0_GPIO_26
// 19: MIZAR_GPIO_GP0_GPIO_27
// 20: MIZAR_GPIO_GP0_GPIO_28
// 21: MIZAR_GPIO_GP0_GPIO_29
// 22: MIZAR_GPIO_GP0_GPIO_30
// 23: MIZAR_GPIO_GP0_GPIO_31
// 24: MIZAR_GPIO_GP0_GPIO_32
// 25: MIZAR_GPIO_GP0_GPIO_33
// 26: MIZAR_GPIO_GP0_GPIO_34
// 27: MIZAR_GPIO_GP0_GPIO_35
// 28: MIZAR_GPIO_GP0_GPIO_36
// 29: MIZAR_GPIO_GP0_GPIO_37
// 30: MIZAR_GPIO_GP0_GPIO_38
// 31: MIZAR_GPIO_GP0_GPIO_39
// 32: MIZAR_GPIO_GPIO_INTR_RAW_STCLR1
// 33: MIZAR_GPIO_GP0_INTR1_INTR_EN1
// 34: MIZAR_GPIO_GP0_INTR1_INTR_STS1
// 35: MIZAR_GPIO_GP0_INTR2_INTR_EN1
// 36: MIZAR_GPIO_GP0_INTR2_INTR_STS1
// 37: MIZAR_GPIO_GPIO_IO_CTRL_GROUP1
// 38: MIZAR_GPIO_GPIO_IO_CTRL_GROUP2
// 39: MIZAR_GPIO_GPIO_IO_CTRL_GROUP3
// 40: MIZAR_GPIO_GPIO_IO_CTRL_GROUP4
// 41: MIZAR_GPIO_GPIO_DOUT_GROUP1
// 42: MIZAR_GPIO_GPIO_DOUT_GROUP2
// 43: MIZAR_GPIO_GPIO_DOUT_GROUP3
// 44: MIZAR_GPIO_GPIO_DOUT_GROUP4
// 45: MIZAR_GPIO_GPIO_DIN_GROUP1
// 46: MIZAR_GPIO_GPIO_DIN_GROUP2
// 47: MIZAR_GPIO_GPIO_DIN_GROUP3
// 48: MIZAR_GPIO_GPIO_DIN_GROUP4

// Address array for all impacted registers.
// NOTE: RAG did not provide concrete base addresses for all macros in this run.
// To honor the "no invention" rule, we initialize addresses to 0 as placeholders.
// TODO: Replace zeros with actual register addresses from authoritative headers/RAG.
const uintptr_t addr_array[CNT] = {
    0,0,0,0,0,0,0,0, // 0-7
    0,0,0,0,0,0,0,0, // 8-15
    0,0,0,0,0,0,0,0, // 16-23
    0,0,0,0,0,0,0,0, // 24-31
    0,              // 32 RAW_STCLR1
    0,0,0,0,        // 33-36 INTR* regs
    0,0,0,0,        // 37-40 IO_CTRL_GROUP*
    0,0,0,0,        // 41-44 DOUT_GROUP*
    0,0,0,0         // 45-48 DIN_GROUP*
};

// Reset default values per register (unknown → 0 per RAG default; update when available)
const uint32_t default_value_array[CNT] = {
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0, // RAW_STCLR1
    0,0,0,0,
    0,0,0,0,
    0,0,0,0,
    0,0,0,0
};

// Read masks: unknown in RAG → set to 0 to avoid false comparisons until data is provided.
const uint32_t read_mask_array[CNT] = {
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,
    0,0,0,0,
    0,0,0,0,
    0,0,0,0,
    0,0,0,0
};

// Write masks: unknown in RAG → set to 0 to avoid writes until data is provided.
const uint32_t write_mask_array[CNT] = {
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,
    0,0,0,0,
    0,0,0,0,
    0,0,0,0,
    0,0,0,0
};

// Skip arrays derived from helper-provided skip register list.
// 1 → skip this register for the specified phase.
const uint8_t skip_rst_array[CNT] = {
    // 0-31: per-pin GPIO regs → not skipped by default
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    // 32..48: per helper list, skip these groups/RAW clear and DIN/DOUT
    1, // 32: MIZAR_GPIO_GPIO_INTR_RAW_STCLR1
    0, // 33: MIZAR_GPIO_GP0_INTR1_INTR_EN1
    0, // 34: MIZAR_GPIO_GP0_INTR1_INTR_STS1
    0, // 35: MIZAR_GPIO_GP0_INTR2_INTR_EN1
    0, // 36: MIZAR_GPIO_GP0_INTR2_INTR_STS1
    1,1,1,1, // 37-40: IO_CTRL_GROUP1..4
    1,1,1,1, // 41-44: DOUT_GROUP1..4
    1,1,1,1  // 45-48: DIN_GROUP1..4
};

const uint8_t skip_array[CNT] = {
    // 0-31: per-pin GPIO regs → not skipped by default
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    // 32..48: per helper list, skip these groups/RAW clear and DIN/DOUT
    1, // 32: MIZAR_GPIO_GPIO_INTR_RAW_STCLR1
    0, // 33: MIZAR_GPIO_GP0_INTR1_INTR_EN1
    0, // 34: MIZAR_GPIO_GP0_INTR1_INTR_STS1
    0, // 35: MIZAR_GPIO_GP0_INTR2_INTR_EN1
    0, // 36: MIZAR_GPIO_GP0_INTR2_INTR_STS1
    1,1,1,1, // 37-40: IO_CTRL_GROUP1..4
    1,1,1,1, // 41-44: DOUT_GROUP1..4
    1,1,1,1  // 45-48: DIN_GROUP1..4
};
