/* Autogenerated GPIO testcase implementation: test_gpio_negedge_intr_en
 * Follows CSV procedure and acceptance criteria exactly. Do not edit manually.
 */

#include "test_define.c"

/* Globals */
static volatile int test_err = 0;
static volatile int int_pend = 0;

/* Small delay utility */
static inline void small_delay(void) {
    for (volatile unsigned int d = 0; d < 10000u; ++d) { __asm__ __volatile__("nop"); }
}

/* Helper: compute per-pin register address offset from base macro */
static inline unsigned int gpio_pin_reg(unsigned int i) {
    return (unsigned int)(MIZAR_GPIO_GP0_GPIO_8 + (i * 4u));
}

/* Default IRQ handler per CSV acceptance criteria */
void Default_IRQHandler(void) {
    int_pend = 0; /* signal ISR observed */

    unsigned int grp = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
    if (grp == 0u) {
        DEBUG_DISPLAY("[ISR] No bits set in group status; unexpected\n");
        test_err++;
    }

    for (unsigned int i = 0; i < 32u; ++i) {
        if ((grp & (1u << i)) == 0u) continue;

        unsigned int raddr = gpio_pin_reg(i);
        unsigned int rdata = read_reg(raddr);

        /* (rdata & 0x1) == 0 */
        if ((rdata & 0x1u) != 0u) {
            DEBUG_DISPLAY("[ISR] GPIO%u: bit0 expected 0 for negedge, got 1\n", i);
            test_err++;
        }
        /* (rdata & 0x2) != 0 */
        if ((rdata & 0x2u) == 0u) {
            DEBUG_DISPLAY("[ISR] GPIO%u: bit1 (negedge status) expected set, got 0\n", i);
            test_err++;
        }

        /* Group status has the bit before clearing */
        unsigned int grp_chk = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
        if ((grp_chk & (1u << i)) == 0u) {
            DEBUG_DISPLAY("[ISR] Group status bit not set for pin %u before clear\n", i);
            test_err++;
        }

        /* Reconfigure and clear raw status for this pin */
        write_reg(raddr, (1u<<20) | (1u<<16));
        write_reg(MIZAR_GPIO_GPIO_INTR_RAW_STCLR1, (1u << i));

        /* After per-pin clear, group should be 0 for this bit (and ideally 0 overall) */
        unsigned int grp_after = read_reg(MIZAR_GPIO_GP0_INTR1_INTR_STS1);
        if ((grp_after & (1u << i)) != 0u) {
            DEBUG_DISPLAY("[ISR] Group status bit persisted after clear for pin %u\n", i);
            test_err++;
        }
    }

    /* Acknowledge at SYSREG and clear GIC */
    write_reg(MIZAR_LSS_SYSREG_RAW_STCR1, 0xFFFFFFFFu);
#ifdef GIC_ClearIRQ
    GIC_ClearIRQ(87);
    GIC_ClearIRQ(88);
#endif
}

void test_case(void) {
#ifdef GIC_EnableIRQ
    GIC_EnableIRQ(87);
    GIC_EnableIRQ(88);
#endif

    /* Enable GPIO interrupts in SYSREG. Prefer using mask macros if available. */
    unsigned int en_mask = 0u;
#ifdef LSS_SYSREG_INTR_EN1_GPIO0_INTR
    en_mask |= LSS_SYSREG_INTR_EN1_GPIO0_INTR;
#endif
#ifdef LSS_SYSREG_INTR_EN1_GPIO1_INTR
    en_mask |= LSS_SYSREG_INTR_EN1_GPIO1_INTR;
#endif
    if (en_mask == 0u) {
        DEBUG_DISPLAY("[SETUP] SYSREG enable mask undefined; writing 0xFFFFFFFF as fallback\n");
        en_mask = 0xFFFFFFFFu; /* fallback if specific masks are unavailable */
    }
    write_reg(MIZAR_LSS_SYSREG_INTR_EN1, en_mask);

    /* Initialize driving register to known value */
    *(volatile unsigned int *)0xA0243FFCu = 0xFFFFFFFFu;

    /* Configure each pin: bits (1u<<20)|(1u<<18)|(1u<<16) per CSV */
    for (unsigned int i = 0; i < 32u; ++i) {
        write_reg(gpio_pin_reg(i), (1u<<20) | (1u<<18) | (1u<<16));
        small_delay();
    }

    /* For each pin: clear raw, enable per-pin, drive edges, and poll for ISR */
    for (unsigned int i = 0; i < 32u; ++i) {
        unsigned int wr_val = (1u << i);
        write_reg(MIZAR_GPIO_GPIO_INTR_RAW_STCLR1, wr_val);
        write_reg(MIZAR_GPIO_GP0_INTR1_INTR_EN1, wr_val);
        small_delay();

        int_pend = 1;
        *(volatile unsigned int *)0xA0243FFCu = 0xFFFFFFFFu; /* set */
        small_delay();
        *(volatile unsigned int *)0xA0243FFCu = ~wr_val;      /* clear bit i to create negedge */

        /* Poll for ISR to clear int_pend */
        unsigned int to = 1000000u;
        while (int_pend && --to) { /* busy-wait */ }
        if (to == 0u) {
            DEBUG_DISPLAY("[POLL] Timeout waiting for ISR on pin %u\n", i);
            test_err++;
        }
    }

    finish(test_err);
}
