/* Autogenerated by Code_Generator Agent (IST 12:14 26-03-2026)
 * Source Test Case: gpio_reg_wr_rd_test
 * Procedure and acceptance derived from CSV. Uses only impacted registers and arrays.
 */
#include "test_define.c"

/* External platform helpers expected:
 *   unsigned int read_reg(unsigned long addr);
 *   void write_reg(unsigned long addr, unsigned int val);
 *   void wait_on(unsigned int n);
 *   void finish(int status);
 */

void test_case(void)
{
    unsigned int def_fail_cnt = 0;
    unsigned int wr_fail_cnt  = 0;

    // Default value check
    for (unsigned int i = 0; i < CNT; ++i)
    {
        unsigned long addr = addr_array[i];
        if (skip_rst_array[i])
            continue; // skip reset-value validation for this index
        if (read_mask_array[i] == 0x00000000)
            continue; // nothing readable

        unsigned int data_rd = read_reg(addr);
        unsigned int data    = (data_rd & 0xFFFFFFFEu);
        unsigned int expect  = default_value_array[i];
        if (data != expect)
        {
#ifdef DEBUG_DISPLAY
            // Log mismatch with index and values
            // printf("DEFVAL MISMATCH: i=%u addr=0x%08lx read=0x%08x exp=0x%08x\n", i, addr, data, expect);
#endif
            def_fail_cnt++;
        }
    }

    // Masked write/read check with test patterns
    const unsigned int patterns[] = {
        0xFFFFFFFFu, 0xAAAAAAAAu, 0x55555555u, 0xF5F5F5F5u, 0xA5A5A5A5u, 0xFFFF0000u
    };

    for (unsigned int p = 0; p < (sizeof(patterns)/sizeof(patterns[0])); ++p)
    {
        unsigned int data_wr = patterns[p];
        for (unsigned int i = 0; i < CNT; ++i)
        {
            unsigned long addr = addr_array[i];
            unsigned int wmask = write_mask_array[i];
            unsigned int rmask = read_mask_array[i];

            if (skip_array[i])
                continue; // functional write/read not applicable
            if (wmask == 0x00000000)
                continue; // non-writable

            write_reg(addr, (data_wr & wmask));

            if ((wmask == 0x00000000) || (rmask == 0x00000000))
                continue; // cannot observe

            unsigned int data_rd = (read_reg(addr) & rmask);
            unsigned int wr_n    = (wmask ^ 0xFFFFFFFFu);
            unsigned int exp_val = ((data_wr & rmask & wmask) | (wr_n & rmask & default_value_array[i]));
            if (data_rd != exp_val)
            {
#ifdef DEBUG_DISPLAY
                // printf("WR/RD MISMATCH: i=%u addr=0x%08lx rd=0x%08x exp=0x%08x pat=0x%08x\n", i, addr, data_rd, exp_val, data_wr);
#endif
                wr_fail_cnt++;
            }
        }
    }

    if ((def_fail_cnt > 0u) || (wr_fail_cnt > 0u))
    {
        finish(1);
    }
    else
    {
        finish(0);
    }
}
